server:
  port: 8020
spring:
  application:
    name: menu
  datasource:
    name: order-online-system
    url: jdbc:mysql://localhost:3306/order_online_system?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true