server:
  port: 8010
spring:
  application:
    name: order
  datasource:
    name: order-online-system
    url: jdbc:mysql://localhost:3306/order_online_system?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true